/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InvestmentPlan {
  'title' : string,
  'features' : Array<string>,
  'vipLevel' : bigint,
  'dailyIncome' : bigint,
  'price' : bigint,
}
export interface Portfolio {
  'balance' : bigint,
  'vipLevel' : bigint,
  'lastUpdated' : Time,
  'dailyProfit' : bigint,
  'totalWithdrawals' : bigint,
  'totalDeposits' : bigint,
  'profits' : bigint,
}
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'status' : TransactionStatus,
  'user' : Principal,
  'reference' : string,
  'txnType' : TransactionType,
  'timestamp' : Time,
  'amount' : bigint,
}
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TransactionType = { 'deposit' : null } |
  { 'withdrawal' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateDailyProfits' : ActorMethod<[], boolean>,
  'deposit' : ActorMethod<[bigint, string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLiveTransactions' : ActorMethod<[], Array<Transaction>>,
  'getPlans' : ActorMethod<[], Array<InvestmentPlan>>,
  'getPortfolio' : ActorMethod<[Principal], [] | [Portfolio]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinPlan' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'withdraw' : ActorMethod<[bigint, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];