/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TransactionStatus,
  'user' : IDL.Principal,
  'reference' : IDL.Text,
  'txnType' : TransactionType,
  'timestamp' : Time,
  'amount' : IDL.Int,
});
export const InvestmentPlan = IDL.Record({
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'vipLevel' : IDL.Nat,
  'dailyIncome' : IDL.Int,
  'price' : IDL.Nat,
});
export const Portfolio = IDL.Record({
  'balance' : IDL.Int,
  'vipLevel' : IDL.Nat,
  'lastUpdated' : Time,
  'dailyProfit' : IDL.Int,
  'totalWithdrawals' : IDL.Int,
  'totalDeposits' : IDL.Int,
  'profits' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateDailyProfits' : IDL.Func([], [IDL.Bool], []),
  'deposit' : IDL.Func([IDL.Int, IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLiveTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getPlans' : IDL.Func([], [IDL.Vec(InvestmentPlan)], ['query']),
  'getPortfolio' : IDL.Func([IDL.Principal], [IDL.Opt(Portfolio)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinPlan' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'withdraw' : IDL.Func([IDL.Int, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TransactionStatus,
    'user' : IDL.Principal,
    'reference' : IDL.Text,
    'txnType' : TransactionType,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  const InvestmentPlan = IDL.Record({
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'vipLevel' : IDL.Nat,
    'dailyIncome' : IDL.Int,
    'price' : IDL.Nat,
  });
  const Portfolio = IDL.Record({
    'balance' : IDL.Int,
    'vipLevel' : IDL.Nat,
    'lastUpdated' : Time,
    'dailyProfit' : IDL.Int,
    'totalWithdrawals' : IDL.Int,
    'totalDeposits' : IDL.Int,
    'profits' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateDailyProfits' : IDL.Func([], [IDL.Bool], []),
    'deposit' : IDL.Func([IDL.Int, IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLiveTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getPlans' : IDL.Func([], [IDL.Vec(InvestmentPlan)], ['query']),
    'getPortfolio' : IDL.Func([IDL.Principal], [IDL.Opt(Portfolio)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinPlan' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'withdraw' : IDL.Func([IDL.Int, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };